#!/usr/bin/env node

var exists = require('fs').exists

var manager = require('download-manager')


// Source versions

const FUSE_VERSION = "2.9.7"


// Source URLs

const FUSE_URL="https://github.com/libfuse/libfuse/releases/download/fuse-"+FUSE_VERSION+"/fuse-"+FUSE_VERSION+".tar.gz"


//
// FUSE
//

var downloads =
[
  {
    name: 'fuse',
    url: FUSE_URL
  }
]


manager(downloads, {path: 'deps'}, function(error)
{
  if(error) throw error;
})
