#!/usr/bin/env node

/**
 * Build `nodeos-barebones` devDependency when it's being used the
 * `nodeos-initramfs` standalone (mostly for development purposses)
 */

const spawn = require('child_process').spawn


const BAREBONES = require('nodeos-barebones')


// http://stackoverflow.com/a/34597104/586382
//
// NPM will run prepublish script after `npm install`
// (https://docs.npmjs.com/misc/scripts). This ensures that when script is
// executed using `npm *` it is run only when the command is `npm install`.
const npm_config_argv = process.env.npm_config_argv
if(npm_config_argv && JSON.parse(npm_config_argv).original[0] === 'install'
|| process.argv[2] === '--force')
  // spawn('npm', ['install', '--production'], {cwd: BAREBONES, stdio: 'inherit'})
  spawn('npm', ['run', 'build'], {cwd: BAREBONES, stdio: 'inherit'})
  .on('exit', function(code, signal)
  {
    process.exit(code || signal)
  })
