#!/usr/bin/env node

var readFileSync = require('fs').readFileSync

var suppose = require('suppose')

var processArguments = require('nodeos-barebones/scripts/processArguments')


const QEMU_SYSTEM = require('qemu')+'/bin/qemu-system-'
const TIMEOUT = 30


var args = processArguments(process.argv.slice(2))

var cpu = args.cpu
var machine = args.machine

var exe
var timeout = setTimeout(function()
{
  exe.kill()

  console.error('Timeout while waiting an answer')
  process.exit(-2)
}, TIMEOUT*1000)


var command = QEMU_SYSTEM+args.cpu_family

var args =
[
//  '-enable-kvm',
  '-nographic',
  '-m', '256M',
  '--kernel', require('nodeos-barebones')+'/out/'+cpu+'/linux',
  '--initrd', 'out/'+cpu,
  '-append',  'console=ttyS0'
]

// // check if kvm is supported
// var kvm = /(vmx|svm)/;
// var contents = "";
//
// try
// {
//   contents = readFileSync('/proc/cpuinfo');
// } catch(e){
//   throw(e);
// }
//
// if(kvm.test(contents) === false)
// {
//   // disable kvm
//   console.log("Your computer does not support kvm. NodeOS will be slower without it.");
//   args.shift();
// }

if(machine) args.unshift('-machine', machine)

exe = suppose(command, args, {debug: process.env.DEBUG !== undefined})
  .when(/NodeOS-boot-singleUserMount> /,
        'setTimeout(console.log, 2000, "this is","a test")\n')
  .when(/this is a test/, function(exe)
  {
    exe.kill()
  })
  .on('error', function(error)
  {
    if(error.message.indexOf('terminating on signal 15 from pid') < 0)
      console.trace(error)
  })
  .end(function()
  {
    clearTimeout(timeout)

    var expects = this.expects.length
    if(expects) process.exit(expects)
  })
